services:
  peeppea_db:
    image: postgres:16
    container_name: peeppea_db
    environment:
      POSTGRES_DB: stars
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: peeppea33
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/database/peeppea_creation:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    networks:
      - peeppea_network
    restart: unless-stopped

  peeppea:
    build:
      context: .
      dockerfile: Dockerfile
    image: peeppea
    depends_on:
      - peeppea_db
    ports:
      - "8080:8080"
    networks:
      - peeppea_network
    restart: unless-stopped

volumes:
  db-data:

networks:
  peeppea_network:
    driver: bridge