services:
  peeppea_db:
    image: postgres:16
    container_name: peeppea_db
    environment:
      POSTGRES_DB: stars
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: peeppea33
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/database/peeppea_creation:/docker-entrypoint-initdb.d
    networks:
      - peeppea_network

  peeppea:
    image: peeppea
    build: .
    depends_on:
      - peeppea_db
    ports:
      - "8080:8080"
    networks:
      - peeppea_network

volumes:
  db-data:

networks:
  peeppea_network:
    driver: bridge
