apiVersion: apps/v1
kind: Deployment
metadata:
  name: peeppea-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peeppea-db
  template:
    metadata:
      labels:
        app: peeppea-db
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_DB
          value: peep-db
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: Peeppea33
        ports:
        - containerPort: 5432
